POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Tesasdfastit",
  "author": "Moikka",
  "url": "www.est.com",
  "likes": 2
}

GET http://localhost:3003/api/blogs

DELETE http://localhost:3003/api/blogs/5e9743f2806eaa4f55baf98a

PUT http://localhost:3003/api/blogs/5e974bac9ecc864ff946fbe3
Content-Type: application/json

{
  "likes": 10
}